export const ActionTypes = {
  SET_BOOK_DATA: "SET_BOOK_DATA",
  SELECTED_BOOK: "SELECTED_BOOK",
  REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",
  EDIT_SELECTED_BOOK: "EDIT_SELECTED_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
  ADD_BOOK: "ADD_BOOK",
};
